spring.application.name=it-num-assessment

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRY_MILLISECONDS}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}